In [1]:
import numpy as np
from scipy.stats import norm

class NaiveBayesClassifier:
    def __init__(self):
        self.class_priors = {}
        self.means = {}
        self.stds = {}

    def fit(self, X, y):
        self.classes = np.unique(y)
        for c in self.classes:
            X_c = X[y == c]
            self.class_priors[c] = len(X_c) / len(X)
            self.means[c] = np.mean(X_c, axis=0)
            self.stds[c] = np.std(X_c, axis=0)

    def calculate_probability(self, x, mean, std):
        return np.prod(norm.pdf(x, loc=mean, scale=std))

    def predict(self, X):
        predictions = []
        for x in X:
            posteriors = []
            for c in self.classes:
                likelihood = self.calculate_probability(x, self.means[c], self.stds[c])
                posterior = likelihood * self.class_priors[c]
                posteriors.append(posterior)
            predictions.append(self.classes[np.argmax(posteriors)])
        return predictions


from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [2]:
# Instantiate and train Naive Bayes classifier
model = NaiveBayesClassifier()
model.fit(X_train, y_train)


In [3]:
def accuracy(y_true, y_pred):
    return np.mean(y_true == y_pred)

# Make predictions
y_pred = model.predict(X_test)

# Evaluate performance
acc = accuracy(y_test, y_pred)
print("Accuracy:", acc)


Accuracy: 1.0


In [4]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
